//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingIt
{
    using System;
    using System.Collections.Generic;
    
    public partial class CraddlePoint
    {
        public int Id { get; set; }
        public string VehicleId { get; set; }
        public string IpAddress { get; set; }
        public string Organization { get; set; }
        public string Provider { get; set; }
    }
}
